name: shellcheck

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: shellcheck *.sh
